### ISSUE TITLE
TypeError: h is not a function

### ISSUE THREAD

**Issue by yingzhiji** [vuejs/vue-cli-plugin-vue-next#1]
The generated mount code was:
```javascript
createApp().mount(
  {
    render: function(h) {
      return h(App)
    }
  },
  '#app'
)
```
which throws an error: `TypeError: h is not a function`.
But the following code was found in [rfcs](https://github.com/vuejs/rfcs/blob/bed289b5e0ff21249a86aefedc1eb25df6ea4db2/active-rfcs/0009-global-api-change.md#after):
```javascript
const app = createApp()

app.mount(App, '#app')
```
When I fixed this, it doesn't throw an error, so should it be fixed?

**Comment by yingzhiji** [comment]
I found that when using the `vue create app` command, if you don't select Babel, the generated code is the first type, and if you choose Babel, the generated code is the second.

**Comment by CaiPeng1989** [comment]
I don't know how or why, but we can write code like this:
```
import {
  createApp,
  // eslint-disable-next-line no-unused-vars
  h
} from 'vue'
import App from './App.vue'

createApp().mount({
  render: () => (
    h(App)
  )
}, '#app')

// OR
createApp().mount({
  setup: () => () => (
    h(App)
  )
}, '#app')
```

**Comment by posva** [comment]
You need to import it: `import { h } from 'vue'`, it's no longer injected (https://github.com/vuejs/rfcs/blob/master/active-rfcs/0008-render-function-api-change.md)
