### ISSUE TITLE
Router: base should be passed to `createHistory`

### ISSUE THREAD

**Issue by ishitatsuyuki** [vuejs/vue-cli-plugin-vue-next#14]
vue-router-next no longer accepts `base` as `RouterOptions`. It has to be specified as the parameter of `createWebHistory` instead.

Additionally, vue-cli currently gives '/' as `BASE_URL` which causes trouble as vue-router-next doesn't seem to like a base with trailing slash. Should be fixed on router side: https://github.com/vuejs/vue-router-next/issues/164

**Comment by posva** [comment]
Let's keep it in one place at https://github.com/vuejs/vue-router-next/issues/164

@sodatea I will take a look and come up with a PR probably

**Comment by ishitatsuyuki** [comment]
@posva The template/codemod needs to be changed on vue-next plugin side.

The linked issue is a separate thing.

**Comment by posva** [comment]
Right, I thought the last comment was unclear about vue-router-next handling the base with a value of `/`, and it does need a change here to handle the no longer existing base option.

To be clear about the `base` value: it should work as before on vue-router-next, so using `/` should work
