### ISSUE TITLE
Can i update vue-next to the lastest version？

### ISSUE THREAD

**Issue by liqiang-p** [vuejs/vue-cli-plugin-vue-next#34]
Hi, vue-next is update version `beta.14` now，but plugin use the `beta.1` , Is there have some method to update the lastest version, I really want to experience new Vue，tks.

**Comment by sodatea** [comment]
`^3.0.0-beta.1` will automatically resolve to the latest `^3.0.0-beta.14` on installation. See https://docs.npmjs.com/about-semantic-versioning
