### ISSUE TITLE
Error while adding the plugin

### ISSUE THREAD

**Issue by ZiFFeL1992** [vuejs/vue-cli-plugin-vue-next#4]
I'm getting this error while adding the plugin:

![image](https://user-images.githubusercontent.com/5492960/72994965-62faaa80-3df8-11ea-898f-f4aa47b4b6a9.png)

```bash
❯ vue --version
@vue/cli 4.1.2
```

**Comment by ZiFFeL1992** [comment]
Nevermind, steps:

1. `vue create <name>`

**Comment by anthonygore** [comment]
Got the same issue but can't resolve it

**Comment by ZiFFeL1992** [comment]
Create an empty vue 2 app, then use `vue add vue-next` to migrate
